---
title: "covid_week1"
author: "Nathan Morgan"
date: "2022-09-13"
output: html_document
---


## Package and Library Setup // File Upload

```{r setup, echo = FALSE}
options(repos = list(CRAN="http://cran.rstudio.com/"))
install.packages("tidyverse")
install.packages("plotly")
install.packages("ggpubr")
library(plotly)
library(tidyverse)
library(dplyr)
library(readr)
library(ggpubr)

# Read data file
covid_data_merged <- read_csv("COVID_data_2022/covid_data_merged.csv", 
  col_types = cols(Confirmed = col_integer(), 
      Deaths = col_integer(), Incident_Rate = col_double(), 
      Total_Test_Results = col_integer(), 
      Case_Fatality_Ratio = col_double(), 
      Testing_Rate = col_double(), POPESTIMATE2019 = col_integer()))

```


## Data Manipulation

```{r manip}
# Log some numbers to get easier data to work with

recode(as.character(covid_data_merged$REGION), X = "5")
recode(as.character(covid_data_merged$DIVISION), X = "10")

logDeaths <- log(covid_data_merged$Deaths)
logConfirmed <- log(covid_data_merged$Confirmed)
logPOPESTIMATE <- log(covid_data_merged$POPESTIMATE2019)

logDF <- data.frame(logConfirmed, logDeaths)

```


## Some Quick Box Plots

```{r box plots}

ggplot(data = covid_data_merged, mapping = aes(x = REGION, y = logPOPESTIMATE, color = REGION)) +
  geom_boxplot() +
  xlab("Region") +
  ylab("2019 Population Estimate")

```


## Multiple Linear Regression Model

```{r analysis}
## Multiple Linear Regression models for deaths, as well as cor test

model <- lm(Deaths ~ Confirmed + Testing_Rate + Total_Test_Results, data = covid_data_merged)
summary(model)

model2 <- lm(Deaths ~ Testing_Rate + Total_Test_Results, data = covid_data_merged)
summary(model2)

cortest <- cor.test(x = covid_data_merged$Confirmed, y = covid_data_merged$Deaths)
cortest

cortest2 <- cor.test(x = logConfirmed, y = logDeaths)
cortest2

```

## Correlation Plots

```{r}

norm_scatter <- ggscatter(covid_data_merged, x = "Deaths", y = "Confirmed",
                         color = "red",
                         add = "reg.line",
                         cor.coef = TRUE, cor.method = "pearson",
                         xlab = "Deaths",
                         ylab = "Confirmed Cases")

log_scatter <- ggscatter(logDF, x = "logDeaths", y = "logConfirmed",
                         color = "red",
                         add = "reg.line",
                         cor.coef = TRUE, cor.method = "pearson",
                         xlab = "Deaths",
                         ylab = "Confirmed Cases")

figure <- ggarrange(norm_scatter, log_scatter)
annotate_figure(figure, top=text_grob("Regression Plots of Confirmed Cases and Deaths"))

```

## Choropleth Maps Displaying Covid Cases per State

```{r choropleth map}

covid_cases = plot_geo(covid_data_merged,
                       locationmode = 'USA-states') %>%
  add_trace(locations = covid_data_merged$State_Code,
            z = covid_data_merged$Confirmed,
            zmin = 0,
            zmax = 12000000,
            color = covid_data_merged$Confirmed) %>%
  layout(geo = list(scope = 'usa'),
         font = list(family = "DM Sans"),
         title = "Confirmed Covid Cases in US\nThrough Sep 2022")

covid_cases

```


## Choropleth Map Displaying Log Transformed Confirmed Cases per State

```{r choroplot map 2}

covid_cases_log = plot_geo(covid_data_merged,
                       locationmode = 'USA-states') %>%
  add_trace(locations = covid_data_merged$State_Code,
            z = logConfirmed,
            zmin = 10,
            zmax = 16,
            color =logConfirmed) %>%
  layout(geo = list(scope = 'usa'),
         font = list(family = "DM Sans"),
         title = "Confirmed Covid Cases in US\nThrough Sep 2022")

covid_cases_log
```


# Create US map of states divided into "divisions"

```{r}

division_map = plot_geo(covid_data_merged,
                      locationmode = 'USA-states') %>%
  add_trace(locations = covid_data_merged$State_Code,
            z = covid_data_merged$DIVISION,
            zmin = 0,
            zmax = 10,
            color = covid_data_merged$DIVISION,
            colorscale = 'Electric') %>%
  layout(geo = list(scope = 'usa'),
         font = list(family = "DM Sans"),
         title = "US State Divisons")

division_map

```


# Create US map of states divided into "regions"

```{r}

region_map = plot_geo(covid_data_merged,
                      locationmode = 'USA-states') %>%
  add_trace(locations = covid_data_merged$State_Code,
            z = covid_data_merged$REGION,
            zmin = 0,
            zmax = 5,
            color = covid_data_merged$REGION,
            colorscale = 'Electric') %>%
  layout(geo = list(scope = 'usa'),
         font = list(family = "DM Sans"),
         title = "US State Regions")

region_map

```

